
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbttraining'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'snowflake'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  dbttraining:
    dstodbt:
      enabled: true
      lkp_busi_dt:
        vars:
          source_model: 'seq_hme_detail'
          hashed_columns:
            is_hashdiff: true
            columns:
              - 'STORE_ID'
              - 'DW_STOREID'
              - 'BUSINESS_DATE'
              - 'OPEN_TIME'
              - 'CLOSE_TIME' 
              - 'TRANSACTION_DATE'
              - 'TRANS_DATE_TXT'
              - 'TRANSACTION_TIME' 
              - 'GREET_DELAY'
              - 'MENU_BOARD_DURATION'
              - 'QUEUE_DURATION'
              - 'CASHIER_WINDOW_DURATION'
              - 'BOOTH_QUEUE_DURATION'
              - 'SERVICE_WINDOW_DURATION'
              - 'TOTAL_BOOTH_DURATION'
              - 'WAITING_AREA_DURATION'
              - 'TRANSACTION_TIME_LKP'
              - 'TOTAL_SPEED_OF_SERVICE_DURATION'
              - 'LANE_NUMBER'
              - 'TBC_LANE'
