{{ config(materialized='view') }}

SELECT  DISTINCT  DW_DAY, DW_FISCALPERIOD,FIRST_VALUE(BUSIDAYDT) over(partition by DW_DAY, DW_FISCALPERIOD order by DW_DAY, DW_FISCALPERIOD) AS BUSIDAYDT
FROM TIME_DAY_DIM