version: 2

sources:
  - name: show_stopper
    description: 'showstopper'
    schema: DBT_SNAMBURI
    tables: 
          - name: time_day_dim
          - name: TIME_DAYPART_DET
          - name: SRC_SEQ_HME_DETAIL
          - name: monthly_sales

  - name: tpch_sample
    database: SNOWFLAKE_SAMPLE_DATA
    schema: DBT_SNAMBURI
    tables:
      - name: LINEITEM
      - name: CUSTOMER
      - name: ORDERS
      - name: PARTSUPP
      - name: SUPPLIER
      - name: PART
      - name: NATION
      - name: REGION