{{ config(materialized='view') }}


{%- set yaml_metadata -%}

source_model: "i_tbc_hme_timer_detail"
sort_columns: "DW_STOREID ASC,DW_TRANS_DAY DESC,TRANS_TIME_TXT ASC"
derived_columns:
    DW_STOREID: 'DW_STOREID'
    DW_BUSI_DAY: 'DW_BUSI_DAY'
    DW_TRANS_DAY: 'DW_TRANS_DAY'
    DW_DAYPART: 'DW_DAYPART'
    OPEN_TIME_TXT: 'OPEN_TIME_TXT'
    CLOSE_TIME_TXT: 'CLOSE_TIME_TXT'
    TRANS_TIME_TXT: 'TRANS_TIME_TXT'
    GREET_DELAY_DUR_SEC: 'GREET_DELAY_DUR_SEC'
    MENU_BOARD_DELAY_DUR_SEC: 'MENU_BOARD_DELAY_DUR_SEC'
    QUEUE_DUR_SEC: 'QUEUE_DUR_SEC'
    CASHIER_WINDOW_DUR_SEC: 'CASHIER_WINDOW_DUR_SEC'
    BOOTH_QUEUE_DUR_SEC: 'BOOTH_QUEUE_DUR_SEC'
    SERV_WINDOW_QUEUE_DUR_SEC: 'SERV_WINDOW_QUEUE_DUR_SEC'
    TOT_BOOTH_DUR_SEC: 'TOT_BOOTH_DUR_SEC'
    WAIT_AREA_DUR_SEC: 'WAIT_AREA_DUR_SEC'
    TOT_SOS_DUR_SECONDS: "TOT_SOS_DUR_SECONDS"
    DRIVE_THRU_LANE_NBR: "DRIVE_THRU_LANE_NBR"
    TBC_LANE: "TBC_LANE"
    CREATE_ID: "CREATE_ID"
    CREATE_TMSTMP: 'CREATE_TMSTMP'
    UPDT_ID: 'UPDT_ID'
    UPDT_TMSTMP: 'UPDT_TMSTMP'
        
{% endset %}

{% set metadata_dict = fromyaml(yaml_metadata) %}

{{ PxSort_macro(metadata_dict) }}