version: 2

sources:
  - name: table_list
    description: 'list of snowflake tables'
    schema: DBT_SNAMBURI
    tables: 
          - name: time_day_dim
          - name: emp
          - name: emp1
          - name: emp2
          - name: emp_src
          